/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router

// Import Routes
import { Route as RootRoute } from './routes/root';
import { Route as HomeRoute } from './pages/home';
import { Route as TicTacRoute } from './pages/TicTac';

// Create/Update Routes
const Home = HomeRoute.update({
  path: '/',
  getParentRoute: () => RootRoute,
} as any);

const TicTac = TicTacRoute.update({
  path: '/tictac',
  getParentRoute: () => RootRoute,
} as any);

// Populate the FileRoutesByPath interface
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof HomeRoute
      parentRoute: typeof RootRoute
    }
    '/tictac': {
      id: '/tictac'
      path: '/tictac'
      fullPath: '/tictac'
      preLoaderRoute: typeof TicTacRoute
      parentRoute: typeof RootRoute
    }
  }
}

// Create and export the route tree
export const routeTree = RootRoute.addChildren({ Home, TicTac });

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "children": [
        "/",
        "/tictac"
      ]
    },
    "/": {
      "filePath": "Home.tsx"
    },
    "/tictac": {
      "filePath": "TicTac.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
